info:
  # Blog Information
  title:        "Spondool"
  subtitle:     "Daily Cashflow Management"
  cover_image:  banner.jpg
  cover_image_caption: ""
  about_image:  banner.jpg
  about_image_caption: ""
  logo:         spondool-logo.png
  
  # Social links
  facebook:     spondool
  twitter:      spondool
  #github:       
  # gplus:        '101183822199340201470'
  
  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  topmail
  
  # Google Analytics tracking ID. Leave blank to disable tracking
  google-analytics-id:	UA-77876918-1
  
  # Sharing settings
  sharing:
    twitter:    true
    facebook:   true
    gplus:      false
    hn:         false
    reddit:     true
    
  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  # google_font: 'Droid+Sans:400,700'
  
  # Setup your fonts, colors etc at _assets/stylesheets/main.scss

# Root URL where the site will be published
url:         https://blog.spondool.com

# host 0.0.0.0 allows us to access site via localhost or 127.0.0.1
host: 0.0.0.0

paginate:             10

# safe mode must be disabled to use jekyll-assets.
safe:               false

#
# jekyll-assets: see more at https://github.com/ixti/jekyll-assets
#
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false

jekyll-crosspost_to_medium:
  enabled: false
  status: draft
